name: 'Deploy'

on:
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  dev-terraform:
    name: 'Dev - Deploy Terraform'
    if: endsWith(github.ref, '/develop')
    runs-on: ubuntu-latest
    container:
      image: cullancarey/website:website-image
      credentials:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    environment: development

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Configure AWS Creds DEV
    - name: Configure AWS Credentials Dev
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/GitHubActionsDeploymentRole-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        role-session-name: terraform-deployment-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        aws-region: ${{ vars.REGION }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config=backend.develop.conf

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate -no-color

      # On push to "main", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply --auto-approve -input=false -var-file="develop.tfvars"


  dev-deploy-files-to-S3:
    name: 'Dev - Deploy files to S3'
    if: endsWith(github.ref, '/develop')
    needs: dev-terraform
    runs-on: ubuntu-latest
    container:
      image: cullancarey/website:website-image
      credentials:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    environment:
      name: development
      url: https://develop.cullancarey.com
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials Dev
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/GitHubActionsDeploymentRole-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        role-session-name: terraform-deployment-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        aws-region: ${{ vars.REGION }}

    - name: Deploy static site to S3 bucket Dev
      run: aws s3 sync ./src/develop/ s3://develop.cullancarey.com --delete --size-only

    - name: Invalidate Cloudfront Cache Dev
      run: aws cloudfront create-invalidation --distribution-id E15AY619D905H7 --paths '/*'


  prod-terraform:
    name: 'Prod - Deploy Terraform'
    if: endsWith(github.ref, '/main')
    runs-on: ubuntu-latest
    container:
      image: cullancarey/website:website-image
      credentials:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Configure AWS Creds PROD
    - name: Configure AWS Credentials PROD
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/GitHubActionsDeploymentRole-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        role-session-name: terraform-deployment-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        aws-region: ${{ vars.REGION }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init -backend-config=backend.main.conf

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate -no-color

      # On push to "main", build or change infrastructure according to Terraform configuration files
    - name: Terraform Apply
      run: terraform apply --auto-approve -input=false -var-file="main.tfvars"


  prod-deploy-files-to-S3:
    name: 'Prod - Deploy files to S3'
    if: endsWith(github.ref, '/main')
    needs: prod-terraform
    runs-on: ubuntu-latest
    container:
      image: cullancarey/website:website-image
      credentials:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    environment:
      name: production
      url: https://cullancarey.com
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials Prod
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ vars.ACCOUNT_ID }}:role/GitHubActionsDeploymentRole-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        role-session-name: terraform-deployment-${{ vars.REGION }}-${{ vars.ACCOUNT_ID }}
        aws-region: ${{ vars.REGION }}

    - name: Deploy static site to S3 bucket Prod
      run: aws s3 sync ./src/main/ s3://cullancarey.com --delete --size-only

    - name: Invalidate Cloudfront Cache Prod
      run: aws cloudfront create-invalidation --distribution-id E1EM2WQ96D3J54 --paths '/*'
