name: Format Code

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  run-black-pylint:
    runs-on: ubuntu-latest
    container:
      image: cullancarey/website:website-image
      credentials:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Run black/pylint/checkov
      run: |
        black Lambdas/*
        pylint --rcfile=.pylintrc Lambdas/contact_form_lambda/*.py
        checkov -d terraform/ --config-file .checkov.yaml
